hazard_categories = {
    "GMO / novel food": "OGM / nouveau aliment",
    "TSEs": "EST",
    "adulteration / fraud": "Adultération / fraude",
    "allergens": "Allergènes",
    "biological contaminants": "Contaminants biologiques",
    "biotoxins (other)": "Biotoxines (autres)",
    "chemical contamination (other)": "Contamination chimique (autres)",
    "composition": "Composition",
    "environmental pollutants": "Polluants environnementaux",
    "feed additives": "Additifs pour l'alimentation animale",
    "food additives and flavourings": "Additifs alimentaires et arômes",
    "foreign bodies": "Corps étrangers",
    "genetically modified": "Génétiquement modifié",
    "heavy metals": "Métaux lourds",
    "industrial contaminants": "Contaminants industriels",
    "labelling absent/incomplete/incorrect": "Étiquetage absent/incomplet/incorrect",
    "migration": "Migration",
    "mycotoxins": "Mycotoxines",
    "natural toxins (other)": "Toxines naturelles (autres)",
    "non-pathogenic micro-organisms": "Micro-organismes non pathogènes",
    "not determined (other)": "Non déterminé (autres)",
    "novel food": "Nouveau aliment",
    "organoleptic aspects": "Aspects organoleptiques",
    "packaging defective / incorrect": "Emballage défectueux / incorrect",
    "parasitic infestation": "Infestation parasitaire",
    "pathogenic micro-organisms": "Micro-organismes pathogènes",
    "pesticide residues": "Résidus de pesticides",
    "poor or insufficient controls": "Contrôles insuffisants ou de mauvaise qualité",
    "radiation": "Radiation",
    "residues of veterinary medicinal": "Résidus de médicaments vétérinaires",
}
