notifying_countries = [
    "Austria (n)",
    "Belgium (n)",
    "Bulgaria (n)",
    "Croatia (n)",
    "Cyprus (n)",
    "Czech Republic (n)",
    "Denmark (n)",
    "EFSA Member (n)",
    "EFTA Surveillance Authority (n)",
    "Estonia (n)",
    "European Commission (n)",
    "Finland (n)",
    "France (n)",
    "Germany (n)",
    "Greece (n)",
    "Hungary (n)",
    "Iceland (n)",
    "Ireland (n)",
    "Italy (n)",
    "Latvia (n)",
    "Liechtenstein (n)",
    "Lithuania (n)",
    "Luxembourg (n)",
    "Malta (n)",
    "Netherlands (n)",
    "Norway (n)",
    "Poland (n)",
    "Portugal (n)",
    "Romania (n)",
    "Slovakia (n)",
    "Slovenia (n)",
    "Spain (n)",
    "Sweden (n)",
    "Switzerland (n)"
]
