origin_countries = [
    "Afghanistan (o)",
    "Albania (o)",
    "Algeria (o)",
    "American Samoa (o)",
    "Andorra (o)",
    "Angola (o)",
    "Anguilla (o)",
    "Antarctica (o)",
    "Antigua and Barbuda (o)",
    "Argentina (o)",
    "Armenia (o)",
    "Aruba (o)",
    "Australia (o)",
    "Austria (o)",
    "Azerbaijan (o)",
    "Bahamas (o)",
    "Bahrain (o)",
    "Bangladesh (o)",
    "Barbados (o)",
    "Belarus (o)",
    "Belgium (o)",
    "Belize (o)",
    "Benin (o)",
    "Bermuda (o)",
    "Bhutan (o)",
    "Bolivia (o)",
    "Bosnia and Herzegovina (o)",
    "Botswana (o)",
    "Bouvet Island (o)",
    "Brazil (o)",
    "British Indian Ocean Territory (o)",
    "British Virgin Islands (o)",
    "Brunei (o)",
    "Bulgaria (o)",
    "Burkina Faso (o)",
    "Burundi (o)",
    "Cambodia (o)",
    "Cameroon (o)",
    "Canada (o)",
    "Cape Verde (o)",
    "Cayman Islands (o)",
    "Central African Republic (o)",
    "Chad (o)",
    "Chile (o)",
    "China (o)",
    "Christmas Island (o)",
    "Cocos (Keeling) Islands (o)",
    "Colombia (o)",
    "Comoros (o)",
    "Congo (Brazzaville) (o)",
    "Cook Islands (o)",
    "Costa Rica (o)",
    "Croatia (o)",
    "Cuba (o)",
    "Curaçao (o)",
    "Cyprus (o)",
    "Czech Republic (o)",
    "Côte d'Ivoire (o)",
    "Democratic Republic of the Congo (o)",
    "Denmark (o)",
    "Djibouti (o)",
    "Dominica (o)",
    "Dominican Republic (o)",
    "EFSA Member (o)",
    "East Timor (o)",
    "Ecuador (o)",
    "Egypt (o)",
    "El Salvador (o)",
    "Equatorial Guinea (o)",
    "Eritrea (o)",
    "Estonia (o)",
    "Ethiopia (o)",
    "Faeroe Islands (o)",
    "Falkland Islands (o)",
    "Fiji (o)",
    "Finland (o)",
    "France (o)",
    "French Guiana (o)",
    "French Polynesia (o)",
    "French Southern and Antarctic Lands (o)",
    "Gabon (o)",
    "Gambia (o)",
    "Georgia (o)",
    "Germany (o)",
    "Ghana (o)",
    "Gibraltar (o)",
    "Greece (o)",
    "Greenland (o)",
    "Grenada (o)",
    "Guadeloupe (o)",
    "Guam (o)",
    "Guatemala (o)",
    "Guernsey (o)",
    "Guinea (o)",
    "Guinea-Bissau (o)",
    "Guyana (o)",
    "Haiti (o)",
    "Heard Island and McDonald Islands (o)",
    "Honduras (o)",
    "Hong Kong (o)",
    "Hungary (o)",
    "Iceland (o)",
    "India (o)",
    "Indonesia (o)",
    "Iran (o)",
    "Iraq (o)",
    "Ireland (o)",
    "Isle of Man (o)",
    "Israel (o)",
    "Italy (o)",
    "Jamaica (o)",
    "Japan (o)",
    "Jersey (o)",
    "Jordan (o)",
    "Kazakhstan (o)",
    "Kenya (o)",
    "Kiribati (o)",
    "Kosovo (o)",
    "Kuwait (o)",
    "Kyrgyzstan (o)",
    "Laos (o)",
    "Latvia (o)",
    "Lebanon (o)",
    "Lesotho (o)",
    "Liberia (o)",
    "Libya (o)",
    "Liechtenstein (o)",
    "Lithuania (o)",
    "Luxembourg (o)",
    "Macao (o)",
    "Madagascar (o)",
    "Malawi (o)",
    "Malaysia (o)",
    "Maldives (o)",
    "Mali (o)",
    "Malta (o)",
    "Marshall Islands (o)",
    "Martinique (o)",
    "Mauritania (o)",
    "Mauritius (o)",
    "Mayotte (o)",
    "Mexico (o)",
    "Micronesia (o)",
    "Moldova (o)",
    "Monaco (o)",
    "Mongolia (o)",
    "Montenegro (o)",
    "Montserrat (o)",
    "Morocco (o)",
    "Mozambique (o)",
    "Myanmar (o)",
    "Namibia (o)",
    "Nauru (o)",
    "Nepal (o)",
    "Netherlands (o)",
    "Netherlands Antilles (o)",
    "New Caledonia (o)",
    "New Zealand (o)",
    "Nicaragua (o)",
    "Niger (o)",
    "Nigeria (o)",
    "Niue (o)",
    "Norfolk Island (o)",
    "North Korea (o)",
    "Northern Ireland (o)",
    "Northern Marianas (o)",
    "Norway (o)",
    "Oman (o)",
    "Pakistan (o)",
    "Palau (o)",
    "Panama (o)",
    "Papua New Guinea (o)",
    "Paraguay (o)",
    "Peru (o)",
    "Philippines (o)",
    "Pitcairn Islands (o)",
    "Poland (o)",
    "Portugal (o)",
    "Puerto Rico (o)",
    "Qatar (o)",
    "Republic of North Macedonia (o)",
    "Romania (o)",
    "Russia (o)",
    "Rwanda (o)",
    "Réunion (o)",
    "Saint Barthélemy (o)",
    "Saint Helena (o)",
    "Saint Kitts and Nevis (o)",
    "Saint Lucia (o)",
    "Saint Martin (o)",
    "Saint Pierre and Miquelon (o)",
    "Saint Vincent and the Grenadines (o)",
    "Samoa (o)",
    "San Marino (o)",
    "Saudi Arabia (o)",
    "Senegal (o)",
    "Serbia (o)",
    "Serbia and Montenegro (o)",
    "Seychelles (o)",
    "Sierra Leone (o)",
    "Singapore (o)",
    "Sint Maarten (o)",
    "Slovakia (o)",
    "Slovenia (o)",
    "Solomon Islands (o)",
    "Somalia (o)",
    "South Africa (o)",
    "South Georgia and the South Sandwich Islands (o)",
    "South Korea (o)",
    "Spain (o)",
    "Sri Lanka (o)",
    "Sudan (o)",
    "Suriname (o)",
    "Svalbard and Jan Mayen (o)",
    "Swaziland (o)",
    "Sweden (o)",
    "Switzerland (o)",
    "Syria (o)",
    "São Tomé and Príncipe (o)",
    "Taiwan (o)",
    "Tajikistan (o)",
    "Tanzania (o)",
    "Thailand (o)",
    "Togo (o)",
    "Tokelau (o)",
    "Tonga (o)",
    "Trinidad and Tobago (o)",
    "Tunisia (o)",
    "Turkmenistan (o)",
    "Turks and Caicos Islands (o)",
    "Tuvalu (o)",
    "Türkiye (o)",
    "US Virgin Islands (o)",
    "Uganda (o)",
    "Ukraine (o)",
    "United Arab Emirates (o)",
    "United Kingdom (o)",
    "United States (o)",
    "United States Minor Outlying Islands (o)",
    "Uruguay (o)",
    "Uzbekistan (o)",
    "Vanuatu (o)",
    "Vatican City (o)",
    "Venezuela (o)",
    "Vietnam (o)",
    "Wallis and Futuna (o)",
    "West Bank and Gaza Strip (o)",
    "Western Sahara (o)",
    "Yemen (o)",
    "Zambia (o)",
    "Zimbabwe (o)",
    "Åland Islands (o)"
]
