product_categories = {
    "alcoholic beverages": "Boissons alcoolisées",
    "animal by-products": "Sous-produits animaux",
    "bivalve molluscs and products thereof": "Mollusques bivalves et leurs produits",
    "cephalopods and products thereof": "Céphalopodes et leurs produits",
    "cereals and bakery products": "Céréales et produits de boulangerie",
    "cocoa and cocoa preparations, coffee and tea": "Cacao et préparations de cacao, café et thé",
    "compound feeds": "Aliments composés",
    "confectionery": "Confiserie",
    "crustaceans and products thereof": "Crustacés et leurs produits",
    "dietetic foods, food supplements and fortified foods": "Aliments diététiques, compléments alimentaires et aliments enrichis",
    "eggs and egg products": "Œufs et produits à base d'œufs",
    "fats and oils": "Graisses et huiles",
    "feed additives": "Additifs pour l'alimentation animale",
    "feed materials": "Matières premières pour aliments",
    "feed premixtures": "Prémélanges pour aliments",
    "fish and fish products": "Poissons et produits à base de poissons",
    "food additives and flavourings": "Additifs alimentaires et arômes",
    "food contact materials": "Matériaux en contact avec les aliments",
    "fruits and vegetables": "Fruits et légumes",
    "gastropods": "Gastéropodes",
    "herbs and spices": "Herbes et épices",
    "honey and royal jelly": "Miel et gelée royale",
    "ices and desserts": "Glaces et desserts",
    "live animals": "Animaux vivants",
    "meat and meat products (other than poultry)": "Viande et produits carnés (autres que volaille)",
    "milk and milk products": "Lait et produits laitiers",
    "natural mineral waters": "Eaux minérales naturelles",
    "non-alcoholic beverages": "Boissons non alcoolisées",
    "nuts, nut products and seeds": "Noix, produits à base de noix et graines",
    "other food product / mixed": "Autres produits alimentaires / mixtes",
    "pet food": "Aliments pour animaux de compagnie",
    "plant protection products": "Produits de protection des plantes",
    "poultry meat and poultry meat products": "Viande de volaille et produits à base de viande de volaille",
    "prepared dishes and snacks": "Plats préparés et snacks",
    "soups, broths, sauces and condiments": "Soupes, bouillons, sauces et condiments",
    "water for human consumption (other)": "Eau pour la consommation humaine (autres)",
    "wine": "Vin",
}
